# Generated by Django 3.2.4 on 2022-12-01 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('text', models.TextField(verbose_name='текст')),
                ('mail', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='время создания')),
            ],
        ),
    ]
