# Generated by Django 3.2 on 2022-11-09 18:06

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='слаг')),
                ('weight', models.PositiveIntegerField(default=100, validators=[catalog.validators.validate_weight], verbose_name='вес')),
                ('canonical_name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='каноническое название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'галерея фото',
                'verbose_name_plural': 'галереи фото',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='слаг')),
                ('canonical_name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='каноническое название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('text', models.TextField(validators=[catalog.validators.validate_amazing], verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='категория')),
                ('gallery_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photo', to='catalog.gallery', verbose_name='галерея')),
                ('tags', models.ManyToManyField(related_name='tags', to='catalog.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
