# Generated by Django 3.2 on 2022-11-10 20:53

import catalog.validators
from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
