# Generated by Django 3.2 on 2022-11-10 21:10

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(validators=[catalog.validators.validate_amazing], verbose_name='описание'),
        ),
    ]
