# Generated by Django 3.2 on 2022-10-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221030_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='Категория',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='Теги',
            field=models.ManyToManyField(related_name='tags', to='catalog.Tag'),
        ),
    ]
