# Generated by Django 3.2 on 2022-10-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221030_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Категория',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Теги',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='catalog.Tag', verbose_name='Теги'),
        ),
    ]
