# Generated by Django 3.2.4 on 2022-11-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_is_on_mane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_on_mane',
            new_name='is_on_main',
        ),
    ]
