# Generated by Django 3.2 on 2022-11-01 19:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20221031_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(verbose_name='каноническое название', max_length=150, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(verbose_name='каноническое название', max_length=150, null=True, blank=True)
        ),
    ]
