# Generated by Django 3.2 on 2022-11-01 20:27

import re
from django.db import migrations


def autocomplite_canonical_name_category(apps, schema_editor):
    Categories = apps.get_model('catalog', 'Category')
    for category in Categories.objects.all():
        category.canonical_name = re.sub(r'[^\s\w]', '', category.name.lower())
        category.save()


def autocomplite_canonical_name_tag(apps, schema_editor):
    Tags = apps.get_model('catalog', 'Tag')
    for tag in Tags.objects.all():
        tag.canonical_name = re.sub(r'[^\s\w]', '', tag.name.lower())
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20221101_2239'),
    ]

    operations = [
        migrations.RunPython(autocomplite_canonical_name_category, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(autocomplite_canonical_name_tag, reverse_code=migrations.RunPython.noop)
    ]
