# Generated by Django 3.2 on 2022-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221101_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(verbose_name='каноническое название', max_length=150, unique=True)
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(verbose_name='каноническое название', max_length=150, unique=True)
        ),
    ]
