# Generated by Django 3.2 on 2022-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221101_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(editable=False, max_length=150, unique=True, verbose_name='каноническое название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(editable=False, max_length=150, unique=True, verbose_name='каноническое название'),
        ),
    ]
